#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_RED_NORMAL 0
#define OBJ_EVENT_GFX_RED_BIKE 1
#define OBJ_EVENT_GFX_RED_SURF 2
#define OBJ_EVENT_GFX_RED_FIELD_MOVE 3
#define OBJ_EVENT_GFX_RED_FISH 4
#define OBJ_EVENT_GFX_RED_VS_SEEKER 5
#define OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE 6
#define OBJ_EVENT_GFX_GREEN_NORMAL 7
#define OBJ_EVENT_GFX_GREEN_BIKE 8
#define OBJ_EVENT_GFX_GREEN_SURF 9
#define OBJ_EVENT_GFX_GREEN_FIELD_MOVE 10
#define OBJ_EVENT_GFX_GREEN_FISH 11
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER 12
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE 13
#define OBJ_EVENT_GFX_RS_BRENDAN 14
#define OBJ_EVENT_GFX_RS_MAY 15
#define OBJ_EVENT_GFX_LITTLE_BOY 16
#define OBJ_EVENT_GFX_LITTLE_GIRL 17
#define OBJ_EVENT_GFX_YOUNGSTER 18
#define OBJ_EVENT_GFX_BOY 19
#define OBJ_EVENT_GFX_BUG_CATCHER 20
#define OBJ_EVENT_GFX_SITTING_BOY 21
#define OBJ_EVENT_GFX_LASS 22
#define OBJ_EVENT_GFX_WOMAN_1 23
#define OBJ_EVENT_GFX_BATTLE_GIRL 24
#define OBJ_EVENT_GFX_MAN 25
#define OBJ_EVENT_GFX_ROCKER 26
#define OBJ_EVENT_GFX_FAT_MAN 27
#define OBJ_EVENT_GFX_WOMAN_2 28
#define OBJ_EVENT_GFX_BEAUTY 29
#define OBJ_EVENT_GFX_BALDING_MAN 30
#define OBJ_EVENT_GFX_WOMAN_3 31
#define OBJ_EVENT_GFX_OLD_MAN_1 32
#define OBJ_EVENT_GFX_OLD_MAN_2 33
#define OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN 34
#define OBJ_EVENT_GFX_OLD_WOMAN 35
#define OBJ_EVENT_GFX_TUBER_M_WATER 36
#define OBJ_EVENT_GFX_TUBER_F 37
#define OBJ_EVENT_GFX_TUBER_M_LAND 38
#define OBJ_EVENT_GFX_CAMPER 39
#define OBJ_EVENT_GFX_PICNICKER 40
#define OBJ_EVENT_GFX_COOLTRAINER_M 41
#define OBJ_EVENT_GFX_COOLTRAINER_F 42
#define OBJ_EVENT_GFX_SWIMMER_M_WATER 43
#define OBJ_EVENT_GFX_SWIMMER_F_WATER 44
#define OBJ_EVENT_GFX_SWIMMER_M_LAND 45
#define OBJ_EVENT_GFX_SWIMMER_F_LAND 46
#define OBJ_EVENT_GFX_WORKER_M 47
#define OBJ_EVENT_GFX_WORKER_F 48
#define OBJ_EVENT_GFX_ROCKET_M 49
#define OBJ_EVENT_GFX_ROCKET_F 50
#define OBJ_EVENT_GFX_GBA_KID 51
#define OBJ_EVENT_GFX_SUPER_NERD 52
#define OBJ_EVENT_GFX_BIKER 53
#define OBJ_EVENT_GFX_BLACKBELT 54
#define OBJ_EVENT_GFX_SCIENTIST 55
#define OBJ_EVENT_GFX_HIKER 56
#define OBJ_EVENT_GFX_FISHER 57
#define OBJ_EVENT_GFX_CHANNELER 58
#define OBJ_EVENT_GFX_CHEF 59
#define OBJ_EVENT_GFX_POLICEMAN 60
#define OBJ_EVENT_GFX_GENTLEMAN 61
#define OBJ_EVENT_GFX_SAILOR 62
#define OBJ_EVENT_GFX_CAPTAIN 63
#define OBJ_EVENT_GFX_NURSE 64
#define OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST 65
#define OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST 66
#define OBJ_EVENT_GFX_UNUSED_MALE_RECEPTIONIST 67
#define OBJ_EVENT_GFX_CLERK 68
#define OBJ_EVENT_GFX_MG_DELIVERYMAN 69
#define OBJ_EVENT_GFX_TRAINER_TOWER_DUDE 70
#define OBJ_EVENT_GFX_PROF_OAK 71
#define OBJ_EVENT_GFX_BLUE 72
#define OBJ_EVENT_GFX_BILL 73
#define OBJ_EVENT_GFX_LANCE 74
#define OBJ_EVENT_GFX_AGATHA 75
#define OBJ_EVENT_GFX_DAISY 76
#define OBJ_EVENT_GFX_LORELEI 77
#define OBJ_EVENT_GFX_MR_FUJI 78
#define OBJ_EVENT_GFX_BRUNO 79
#define OBJ_EVENT_GFX_BROCK 80
#define OBJ_EVENT_GFX_MISTY 81
#define OBJ_EVENT_GFX_LT_SURGE 82
#define OBJ_EVENT_GFX_ERIKA 83
#define OBJ_EVENT_GFX_KOGA 84
#define OBJ_EVENT_GFX_SABRINA 85
#define OBJ_EVENT_GFX_BLAINE 86
#define OBJ_EVENT_GFX_GIOVANNI 87
#define OBJ_EVENT_GFX_MOM 88
#define OBJ_EVENT_GFX_CELIO 89
#define OBJ_EVENT_GFX_TEACHY_TV_HOST 90
#define OBJ_EVENT_GFX_GYM_GUY 91
#define OBJ_EVENT_GFX_ITEM_BALL 92
#define OBJ_EVENT_GFX_TOWN_MAP 93
#define OBJ_EVENT_GFX_POKEDEX 94
#define OBJ_EVENT_GFX_CUT_TREE 95
#define OBJ_EVENT_GFX_ROCK_SMASH_ROCK 96
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER 97
#define OBJ_EVENT_GFX_FOSSIL 98
#define OBJ_EVENT_GFX_RUBY 99
#define OBJ_EVENT_GFX_SAPPHIRE 100
#define OBJ_EVENT_GFX_OLD_AMBER 101
#define OBJ_EVENT_GFX_GYM_SIGN 102
#define OBJ_EVENT_GFX_SIGN 103
#define OBJ_EVENT_GFX_TRAINER_TIPS 104
#define OBJ_EVENT_GFX_CLIPBOARD 105
#define OBJ_EVENT_GFX_METEORITE 106
#define OBJ_EVENT_GFX_LAPRAS_DOLL 107
#define OBJ_EVENT_GFX_SEAGALLOP 108
#define OBJ_EVENT_GFX_SNORLAX 109
#define OBJ_EVENT_GFX_SPEAROW 110
#define OBJ_EVENT_GFX_CUBONE 111
#define OBJ_EVENT_GFX_POLIWRATH 112
#define OBJ_EVENT_GFX_CLEFAIRY 113
#define OBJ_EVENT_GFX_PIDGEOT 114
#define OBJ_EVENT_GFX_JIGGLYPUFF 115
#define OBJ_EVENT_GFX_PIDGEY 116
#define OBJ_EVENT_GFX_CHANSEY 117
#define OBJ_EVENT_GFX_OMANYTE 118
#define OBJ_EVENT_GFX_KANGASKHAN 119
#define OBJ_EVENT_GFX_PIKACHU 120
#define OBJ_EVENT_GFX_PSYDUCK 121
#define OBJ_EVENT_GFX_NIDORAN_F 122
#define OBJ_EVENT_GFX_NIDORAN_M 123
#define OBJ_EVENT_GFX_NIDORINO 124
#define OBJ_EVENT_GFX_MEOWTH 125
#define OBJ_EVENT_GFX_SEEL 126
#define OBJ_EVENT_GFX_VOLTORB 127
#define OBJ_EVENT_GFX_SLOWPOKE 128
#define OBJ_EVENT_GFX_SLOWBRO 129
#define OBJ_EVENT_GFX_MACHOP 130
#define OBJ_EVENT_GFX_WIGGLYTUFF 131
#define OBJ_EVENT_GFX_DODUO 132
#define OBJ_EVENT_GFX_FEAROW 133
#define OBJ_EVENT_GFX_MACHOKE 134
#define OBJ_EVENT_GFX_LAPRAS 135
#define OBJ_EVENT_GFX_ZAPDOS 136
#define OBJ_EVENT_GFX_MOLTRES 137
#define OBJ_EVENT_GFX_ARTICUNO 138
#define OBJ_EVENT_GFX_MEWTWO 139
#define OBJ_EVENT_GFX_MEW 140
#define OBJ_EVENT_GFX_ENTEI 141
#define OBJ_EVENT_GFX_SUICUNE 142
#define OBJ_EVENT_GFX_RAIKOU 143
#define OBJ_EVENT_GFX_LUGIA 144
#define OBJ_EVENT_GFX_HO_OH 145
#define OBJ_EVENT_GFX_CELEBI 146
#define OBJ_EVENT_GFX_KABUTO 147
#define OBJ_EVENT_GFX_DEOXYS_D 148
#define OBJ_EVENT_GFX_DEOXYS_A 149
#define OBJ_EVENT_GFX_DEOXYS_N 150
#define OBJ_EVENT_GFX_SS_ANNE 151

#define OBJ_EVENT_GFX_ITEM_BALL_HIDDEN 				152
#define OBJ_EVENT_GFX_ITEM_BALL_BURIED 				153

#define OBJ_EVENT_GFX_AVATAR_NORMAL					154
#define OBJ_EVENT_GFX_AVATAR_MACH_BIKE				155
#define OBJ_EVENT_GFX_AVATAR_SURFING				156
#define OBJ_EVENT_GFX_AVATAR_FIELD_MOVE				157
#define OBJ_EVENT_GFX_AVATAR_FISHING				158
#define OBJ_EVENT_GFX_AVATAR_VS_SEEKER				159
#define OBJ_EVENT_GFX_AVATAR_VS_SEEKER_BIKE			160

#define NUM_OBJ_EVENT_GFX     						161

#define OBJ_EVENT_GFX_BRENDAN_NORMAL				0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE				1
#define OBJ_EVENT_GFX_BRENDAN_SURFING				2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE			3
#define OBJ_EVENT_GFX_BRENDAN_FISHING				4
#define OBJ_EVENT_GFX_BRENDAN_VS_SEEKER				5
#define OBJ_EVENT_GFX_BRENDAN_VS_SEEKER_BIKE		6

#define OBJ_EVENT_GFX_MAY_NORMAL					7
#define OBJ_EVENT_GFX_MAY_MACH_BIKE					8
#define OBJ_EVENT_GFX_MAY_SURFING					9
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE				10
#define OBJ_EVENT_GFX_MAY_FISHING					11
#define OBJ_EVENT_GFX_MAY_VS_SEEKER					12
#define OBJ_EVENT_GFX_MAY_VS_SEEKER_BIKE			13

#define OBJ_EVENT_GFX_BLUE_NORMAL					14
#define OBJ_EVENT_GFX_BLUE_MACH_BIKE				15
#define OBJ_EVENT_GFX_BLUE_SURFING					16
#define OBJ_EVENT_GFX_BLUE_FIELD_MOVE				17
#define OBJ_EVENT_GFX_BLUE_FISHING					18
#define OBJ_EVENT_GFX_BLUE_VS_SEEKER				19
#define OBJ_EVENT_GFX_BLUE_VS_SEEKER_BIKE			20

#define OBJ_EVENT_GFX_ETHAN_NORMAL					21
#define OBJ_EVENT_GFX_ETHAN_MACH_BIKE				22
#define OBJ_EVENT_GFX_ETHAN_SURFING					23
#define OBJ_EVENT_GFX_ETHAN_FIELD_MOVE				24
#define OBJ_EVENT_GFX_ETHAN_FISHING					25
#define OBJ_EVENT_GFX_ETHAN_VS_SEEKER				26
#define OBJ_EVENT_GFX_ETHAN_VS_SEEKER_BIKE			27

#define OBJ_EVENT_GFX_RS_BRENDAN_NORMAL				28
#define OBJ_EVENT_GFX_RS_BRENDAN_MACH_BIKE			29
#define OBJ_EVENT_GFX_RS_BRENDAN_SURFING			30
#define OBJ_EVENT_GFX_RS_BRENDAN_FIELD_MOVE			31
#define OBJ_EVENT_GFX_RS_BRENDAN_FISHING			32
#define OBJ_EVENT_GFX_RS_BRENDAN_VS_SEEKER			33
#define OBJ_EVENT_GFX_RS_BRENDAN_VS_SEEKER_BIKE		34

#define OBJ_EVENT_GFX_RS_MAY_NORMAL					35
#define OBJ_EVENT_GFX_RS_MAY_MACH_BIKE				36
#define OBJ_EVENT_GFX_RS_MAY_SURFING				37
#define OBJ_EVENT_GFX_RS_MAY_FIELD_MOVE				38
#define OBJ_EVENT_GFX_RS_MAY_FISHING				39
#define OBJ_EVENT_GFX_RS_MAY_VS_SEEKER				40
#define OBJ_EVENT_GFX_RS_MAY_VS_SEEKER_BIKE			41

#define OBJ_EVENT_GFX_RS_BLUE_MAY_NORMAL			42
#define OBJ_EVENT_GFX_RS_BLUE_MAY_MACH_BIKE			43
#define OBJ_EVENT_GFX_RS_BLUE_MAY_SURFING			44
#define OBJ_EVENT_GFX_RS_BLUE_MAY_FIELD_MOVE		45
#define OBJ_EVENT_GFX_RS_BLUE_MAY_FISHING			46
#define OBJ_EVENT_GFX_RS_BLUE_MAY_VS_SEEKER			47
#define OBJ_EVENT_GFX_RS_BLUE_MAY_VS_SEEKER_BIKE	48

#define OBJ_EVENT_GFX_DAWN_NORMAL					49
#define OBJ_EVENT_GFX_DAWN_MACH_BIKE				50
#define OBJ_EVENT_GFX_DAWN_SURFING					51
#define OBJ_EVENT_GFX_DAWN_FIELD_MOVE				52
#define OBJ_EVENT_GFX_DAWN_FISHING					53
#define OBJ_EVENT_GFX_DAWN_VS_SEEKER				54
#define OBJ_EVENT_GFX_DAWN_VS_SEEKER_BIKE			55

#define OBJ_EVENT_GFX_LUCAS_NORMAL					56
#define OBJ_EVENT_GFX_LUCAS_MACH_BIKE				57
#define OBJ_EVENT_GFX_LUCAS_SURFING					58
#define OBJ_EVENT_GFX_LUCAS_FIELD_MOVE				59
#define OBJ_EVENT_GFX_LUCAS_FISHING					60
#define OBJ_EVENT_GFX_LUCAS_VS_SEEKER				61
#define OBJ_EVENT_GFX_LUCAS_VS_SEEKER_BIKE			62

#define OBJ_EVENT_GFX_LYRA_NORMAL					63
#define OBJ_EVENT_GFX_LYRA_MACH_BIKE				64
#define OBJ_EVENT_GFX_LYRA_SURFING					65
#define OBJ_EVENT_GFX_LYRA_FIELD_MOVE				66
#define OBJ_EVENT_GFX_LYRA_FISHING					67
#define OBJ_EVENT_GFX_LYRA_VS_SEEKER				68
#define OBJ_EVENT_GFX_LYRA_VS_SEEKER_BIKE			69

#define OBJ_EVENT_GFX_PEACH_NORMAL					70
#define OBJ_EVENT_GFX_PEACH_MACH_BIKE				71
#define OBJ_EVENT_GFX_PEACH_SURFING					72
#define OBJ_EVENT_GFX_PEACH_FIELD_MOVE				73
#define OBJ_EVENT_GFX_PEACH_FISHING					74
#define OBJ_EVENT_GFX_PEACH_VS_SEEKER				75
#define OBJ_EVENT_GFX_PEACH_VS_SEEKER_BIKE			76

#define OBJ_EVENT_GFX_YUGI_NORMAL					77
#define OBJ_EVENT_GFX_YUGI_MACH_BIKE				78
#define OBJ_EVENT_GFX_YUGI_SURFING					79
#define OBJ_EVENT_GFX_YUGI_FIELD_MOVE				80
#define OBJ_EVENT_GFX_YUGI_FISHING					81
#define OBJ_EVENT_GFX_YUGI_VS_SEEKER				82
#define OBJ_EVENT_GFX_YUGI_VS_SEEKER_BIKE			83

#define OBJ_EVENT_GFX_RETRORED_NORMAL				84
#define OBJ_EVENT_GFX_RETRORED_MACH_BIKE			85
#define OBJ_EVENT_GFX_RETRORED_SURFING				86
#define OBJ_EVENT_GFX_RETRORED_FIELD_MOVE			87
#define OBJ_EVENT_GFX_RETRORED_FISHING				88
#define OBJ_EVENT_GFX_RETRORED_VS_SEEKER			89
#define OBJ_EVENT_GFX_RETRORED_VS_SEEKER_BIKE		90

#define OBJ_EVENT_GFX_ARCHIE_NORMAL					91
#define OBJ_EVENT_GFX_ARCHIE_MACH_BIKE				92
#define OBJ_EVENT_GFX_ARCHIE_SURFING				93
#define OBJ_EVENT_GFX_ARCHIE_FIELD_MOVE				94
#define OBJ_EVENT_GFX_ARCHIE_FISHING				95
#define OBJ_EVENT_GFX_ARCHIE_VS_SEEKER				96
#define OBJ_EVENT_GFX_ARCHIE_VS_SEEKER_BIKE			97

#define OBJ_EVENT_GFX_DUSCLOPS_NORMAL				98
#define OBJ_EVENT_GFX_DUSCLOPS_MACH_BIKE			99
#define OBJ_EVENT_GFX_DUSCLOPS_SURFING				100
#define OBJ_EVENT_GFX_DUSCLOPS_FIELD_MOVE			101
#define OBJ_EVENT_GFX_DUSCLOPS_FISHING				102
#define OBJ_EVENT_GFX_DUSCLOPS_VS_SEEKER			103
#define OBJ_EVENT_GFX_DUSCLOPS_VS_SEEKER_BIKE		104

#define OBJ_EVENT_GFX_LORELEI_NORMAL				105
#define OBJ_EVENT_GFX_LORELEI_MACH_BIKE				106
#define OBJ_EVENT_GFX_LORELEI_SURFING				107
#define OBJ_EVENT_GFX_LORELEI_FIELD_MOVE			108
#define OBJ_EVENT_GFX_LORELEI_FISHING				109
#define OBJ_EVENT_GFX_LORELEI_VS_SEEKER				110
#define OBJ_EVENT_GFX_LORELEI_VS_SEEKER_BIKE		111

#define OBJ_EVENT_GFX_MAXIE_NORMAL					112
#define OBJ_EVENT_GFX_MAXIE_MACH_BIKE				113
#define OBJ_EVENT_GFX_MAXIE_SURFING					114
#define OBJ_EVENT_GFX_MAXIE_FIELD_MOVE				115
#define OBJ_EVENT_GFX_MAXIE_FISHING					116
#define OBJ_EVENT_GFX_MAXIE_VS_SEEKER				117
#define OBJ_EVENT_GFX_MAXIE_VS_SEEKER_BIKE			118

#define OBJ_EVENT_GFX_OAK_NORMAL					119
#define OBJ_EVENT_GFX_OAK_MACH_BIKE					120
#define OBJ_EVENT_GFX_OAK_SURFING					121
#define OBJ_EVENT_GFX_OAK_FIELD_MOVE				122
#define OBJ_EVENT_GFX_OAK_FISHING					123
#define OBJ_EVENT_GFX_OAK_VS_SEEKER					124
#define OBJ_EVENT_GFX_OAK_VS_SEEKER_BIKE			125

#define OBJ_EVENT_GFX_STEVEN_NORMAL					126
#define OBJ_EVENT_GFX_STEVEN_MACH_BIKE				127
#define OBJ_EVENT_GFX_STEVEN_SURFING				128
#define OBJ_EVENT_GFX_STEVEN_FIELD_MOVE				129
#define OBJ_EVENT_GFX_STEVEN_FISHING				130
#define OBJ_EVENT_GFX_STEVEN_VS_SEEKER				131
#define OBJ_EVENT_GFX_STEVEN_VS_SEEKER_BIKE			132

#define OBJ_EVENT_GFX_WALLACE_NORMAL				133
#define OBJ_EVENT_GFX_WALLACE_MACH_BIKE				134
#define OBJ_EVENT_GFX_WALLACE_SURFING				135
#define OBJ_EVENT_GFX_WALLACE_FIELD_MOVE			136
#define OBJ_EVENT_GFX_WALLACE_FISHING				137
#define OBJ_EVENT_GFX_WALLACE_VS_SEEKER				138
#define OBJ_EVENT_GFX_WALLACE_VS_SEEKER_BIKE		139

#define OBJ_EVENT_GFX_WALLY_NORMAL					140
#define OBJ_EVENT_GFX_WALLY_MACH_BIKE				141
#define OBJ_EVENT_GFX_WALLY_SURFING					142
#define OBJ_EVENT_GFX_WALLY_FIELD_MOVE				143
#define OBJ_EVENT_GFX_WALLY_FISHING					144
#define OBJ_EVENT_GFX_WALLY_VS_SEEKER				145
#define OBJ_EVENT_GFX_WALLY_VS_SEEKER_BIKE			146

#define OBJ_EVENT_GFX_ZIGZAG_NORMAL					147
#define OBJ_EVENT_GFX_ZIGZAG_MACH_BIKE				148
#define OBJ_EVENT_GFX_ZIGZAG_SURFING				149
#define OBJ_EVENT_GFX_ZIGZAG_FIELD_MOVE				150
#define OBJ_EVENT_GFX_ZIGZAG_FISHING				151
#define OBJ_EVENT_GFX_ZIGZAG_VS_SEEKER				152
#define OBJ_EVENT_GFX_ZIGZAG_VS_SEEKER_BIKE			153

#define OBJ_EVENT_GFX_KRIS_NORMAL					154
#define OBJ_EVENT_GFX_KRIS_MACH_BIKE				155
#define OBJ_EVENT_GFX_KRIS_SURFING					156
#define OBJ_EVENT_GFX_KRIS_FIELD_MOVE				157
#define OBJ_EVENT_GFX_KRIS_FISHING					158
#define OBJ_EVENT_GFX_KRIS_VS_SEEKER				159
#define OBJ_EVENT_GFX_KRIS_VS_SEEKER_BIKE			160

#define OBJ_EVENT_GFX_BARRY_NORMAL					161
#define OBJ_EVENT_GFX_BARRY_MACH_BIKE				162
#define OBJ_EVENT_GFX_BARRY_SURFING					163
#define OBJ_EVENT_GFX_BARRY_FIELD_MOVE				164
#define OBJ_EVENT_GFX_BARRY_FISHING					165
#define OBJ_EVENT_GFX_BARRY_VS_SEEKER				166
#define OBJ_EVENT_GFX_BARRY_VS_SEEKER_BIKE			167

#define OBJ_EVENT_GFX_CYNTHIA_NORMAL				168
#define OBJ_EVENT_GFX_CYNTHIA_MACH_BIKE				169
#define OBJ_EVENT_GFX_CYNTHIA_SURFING				170
#define OBJ_EVENT_GFX_CYNTHIA_FIELD_MOVE			171
#define OBJ_EVENT_GFX_CYNTHIA_FISHING				172
#define OBJ_EVENT_GFX_CYNTHIA_VS_SEEKER				173
#define OBJ_EVENT_GFX_CYNTHIA_VS_SEEKER_BIKE		174

#define OBJ_EVENT_GFX_LANCE_NORMAL					175
#define OBJ_EVENT_GFX_LANCE_MACH_BIKE				176
#define OBJ_EVENT_GFX_LANCE_SURFING					177
#define OBJ_EVENT_GFX_LANCE_FIELD_MOVE				178
#define OBJ_EVENT_GFX_LANCE_FISHING					179
#define OBJ_EVENT_GFX_LANCE_VS_SEEKER				180
#define OBJ_EVENT_GFX_LANCE_VS_SEEKER_BIKE			181

#define OBJ_EVENT_GFX_SILVER_NORMAL					182
#define OBJ_EVENT_GFX_SILVER_MACH_BIKE				183
#define OBJ_EVENT_GFX_SILVER_SURFING				184
#define OBJ_EVENT_GFX_SILVER_FIELD_MOVE				185
#define OBJ_EVENT_GFX_SILVER_FISHING				186
#define OBJ_EVENT_GFX_SILVER_VS_SEEKER				187
#define OBJ_EVENT_GFX_SILVER_VS_SEEKER_BIKE			188

#define AVATAR_RED   			0
#define AVATAR_GREEN 			1
#define AVATAR_BRENDAN   		2
#define AVATAR_MAY 				3
#define AVATAR_BLUE 			4
#define AVATAR_ETHAN 			5
#define AVATAR_RS_BRENDAN   	6
#define AVATAR_RS_MAY 			7
#define AVATAR_RS_MAY_BLUE		8
#define AVATAR_DAWN				9
#define AVATAR_LUCAS			10
#define AVATAR_LYRA				11
#define AVATAR_PEACH			12
#define AVATAR_YUGI				13
#define AVATAR_RETRORED			14
#define AVATAR_ARCHIE			15
#define AVATAR_DUSCLOPS			16
#define AVATAR_LORELEI			17
#define AVATAR_MAXIE			18
#define AVATAR_OAK				19
#define AVATAR_STEVEN			20
#define AVATAR_WALLACE			21
#define AVATAR_WALLY			22
#define AVATAR_ZIGZAG			23
#define AVATAR_KRIS				24
#define AVATAR_BARRY			25
#define AVATAR_CYNTHIA			26
#define AVATAR_LANCE			27
#define AVATAR_SILVER			28

#define AVATAR_COUNT 			29

#define NUM_AVATAR_GFX     		(AVATAR_COUNT-2)*7

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   240
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define OBJ_EVENT_ID_PLAYER  0xFF
#define OBJ_EVENT_ID_CAMERA  0x7F

#endif // GUARD_CONSTANTS_EVENT_OBJECTS_H
