#ifndef GUARD_ITEMFINDER_H
#define GUARD_ITEMFINDER_H

void ItemUseOnFieldCB_Itemfinder(u8 taskId);

#define OBJ_EVENT_ID_SHOWITEMFINDER_1  0xF7
#define OBJ_EVENT_ID_SHOWITEMFINDER_2  0xF8
#define OBJ_EVENT_ID_SHOWITEMFINDER_3  0xF9
#define OBJ_EVENT_ID_SHOWITEMFINDER_4  0xFA
#define OBJ_EVENT_ID_SHOWITEMFINDER_5  0xFB
#define OBJ_EVENT_ID_SHOWITEMFINDER_6  0xFC
#define OBJ_EVENT_ID_SHOWITEMFINDER_7  0xFD
#define OBJ_EVENT_ID_SHOWITEMFINDER_8  0xFE

#endif //GUARD_ITEMFINDER_H
