name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clone agbcc
        uses: actions/checkout@v2
        with:
          repository: pret/agbcc
          path: deps/agbcc

      - name: Clone upstream
        uses: actions/checkout@v2
        with:
          repository: pret/pokefirered
          path: deps/upstream

      - name: Clone rando
        uses: actions/checkout@v2
        with:
          repository: dabomstew/upr-speedchoice
          ref: master
          path: UPR

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 8

      - name: Install deps
        run: sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev xdelta3

      - name: Build agbcc
        run: |
          cd deps/agbcc
          ./build.sh

      - name: Install agbcc
        run: |
          cd deps/agbcc
          ./install.sh ../../

      - name: Install agbcc to upstream
        run: |
          cd deps/agbcc
          ./install.sh ../upstream

      - name: Install launch4j
        run: |
          cd deps
          curl https://versaweb.dl.sourceforge.net/project/launch4j/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz | tar -xzv

      - name: Build baserom
        run: make -C deps/upstream compare_firered_rev1 -j${nproc}

      - name: Build
        run: |
          cp deps/upstream/pokefirered_rev1.gba baserom.gba
          cp -r deps/launch4j UPR/launch4j
          make -j${nproc} release UPRDIR=UPR

      - name: Package Release
        run: |
          read addr size type name <<< $(nm -SBgn pokefirered-speedchoice.elf | grep -w gSpeedchoiceVersion)
          verstr=$(dd if=pokefirered-speedchoice.gba bs=1 skip=$((0x${addr} & 0xFFFFFF)) count=$((0x${size} - 1)))
          export relname=pokemon-firered-speedchoice-${verstr}-plus-randomizer
          mkdir ${relname}
          cp -r pokefirered-speedchoice.xdelta UPR/build/$(date '+%Y%m%d')/* ${relname}/
          zip -r ${relname}.zip ${relname}/

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: pokemon-firered-speedchoice-*-plus-randomizer.zip
